### PR TITLE
issue resolved #6

### LINKED ISSUE #6: white vertical bar on the home page
Go to soulsion.com
Notice that there is a vertical white bar on the left side of the quote.

Can you fix this? Have a look at the code at ```front-end/src/components/homepage/homepage-top-header.js```, class ```Quote```.
I think this is some bootstrap issue.

### PR DESCRIPTION
**Pull request by av1shek**
white vertical bar on the home page #6
By default blockquote tag in html has that property if we don't want we have to override that property.

### CODE REVIEW

**Comment by sauravshah31** [comment]
Instead of removing the border from the blockquote in general, I think you could add a class to the quote block, and remove it's border instead?

**Comment by av1shek** [comment]
> Instead of removing the border from the blockquote in general, I think you could add a class to the quote block, and remove it's border instead?

ya you are right, i will change.

**Comment by av1shek** [comment]
blockquote has already a class given "quote", so I think it will be good if I will add css to "quote" class . But what's your suggestion should I give some other class and then add css or it will be fine if I will add css in "quote" class ?

**Comment by sauravshah31** [comment]
> 
> 
> blockquote has already a class given "quote", so I think it will be good if I will add css to "quote" class . But what's your suggestion should I give some other class and then add css or it will be fine if I will add css in "quote" class ?

Yes, You can add the css to the existing quote class. I don't think 'quote' class is used anywhere else, to this should be fine.

**Comment by av1shek** [comment]
ok 1 min

> > blockquote has already a class given "quote", so I think it will be good if I will add css to "quote" class . But what's your suggestion should I give some other class and then add css or it will be fine if I will add css in "quote" class ?
> 
> Yes, You can add the css to the existing quote class. I don't think 'quote' class is used anywhere else, to this should be fine.

ok, thanks I m deleting this fork.

**Comment by sauravshah31** [comment]
> ok, thanks I m deleting this fork.

You don't have to delete the fork. I have already closed this PR, just send another PR after making the changes.

**Pull request closed without merging**
